#!/bin/bash

continue='Already up-to-date.'

function submitTurn {
  echo 'Submitting game data...'
  git add gitwar.log &> /dev/null
  git commit -m "$1" &> /dev/null
  git push origin master &> /dev/null
}

function silentSubmit {
  git add gitwar.log &> /dev/null
  git commit -m "$1" &> /dev/null
  git push origin master &> /dev/null
}

function silentPull {
  git pull origin master &> /dev/null
}

function wait {
  echo -n 'Waiting for opponent to make their move...'
  while [ "$continue" = 'Already up-to-date.' ]; do
    continue=`git pull origin master 2> /dev/null`
  done

  # Call the app who called me and tell them the opponent took their turn

  echo
}

function reset {
  echo "Resetting game - make sure your opponent pulls the latest changes before they start playing"
  heading=`head -1 gitwar.log`
  echo "$heading" > gitwar.log
  git add gitwar.log &> /dev/null
  git commit -m 'Resetting game' &> /dev/null
  git push origin master &> /dev/null
}

if [ "$1" = "-w" ]; then
  wait
elif [ "$1" = "-c" ]; then
  reset
elif [ "$1" = "-s" ]; then
  silentSubmit "$2"
elif [ "$1" = "-p" ]; then
  silentPull
else
  submitTurn "$1"
  wait
fi
