#!/bin/bash

grid=(
'row=(rook knight bishop king queen bishop knight rook)'
'row=(pawn pawn pawn pawn pawn pawn pawn pawn)'
'row=(blank blank blank blank blank blank blank blank)'
'row=(blank blank blank blank blank blank blank blank)'
'row=(blank blank blank blank blank blank blank blank)'
'row=(blank blank blank blank blank blank blank blank)'
'row=(PAWN PAWN PAWN PAWN PAWN PAWN PAWN PAWN)'
'row=(ROOK KNIGHT BISHOP QUEEN KING BISHOP KNIGHT ROOK)'
)

function flipBoard {
  i=7
  newGrid=()
  for j in {0..7}; do
    newRow=()
    k=7
    eval ${grid[j]}
    for w in {0..7}; do
      newRow[$k]=${row[w]}
      k=`expr $k - 1`
    done

    newGrid[$i]='row=('${newRow[@]}')'
    i=`expr $i - 1`
  done
  for j in {0..7}; do
    grid[$j]=${newGrid[j]}
  done
}

function getPiece {
  if [ "$1" = "king" ]; then
    piece=`echo -e "\xE2\x99\x94"`
  elif [ "$1" = "queen" ]; then
    piece=`echo -e "\xE2\x99\x95"`
  elif [ "$1" = "rook" ]; then
    piece=`echo -e "\xE2\x99\x96"`
  elif [ "$1" = "bishop" ]; then
    piece=`echo -e "\xE2\x99\x97"`
  elif [ "$1" = "knight" ]; then
    piece=`echo -e "\xE2\x99\x98"`
  elif [ "$1" = "pawn" ]; then
    piece=`echo -e "\xE2\x99\x99"`
  elif [ "$1" = "KING" ]; then
    piece=`echo -e "\xE2\x99\x9A"`
  elif [ "$1" = "QUEEN" ]; then
    piece=`echo -e "\xE2\x99\x9B"`
  elif [ "$1" = "ROOK" ]; then
    piece=`echo -e "\xE2\x99\x9C"`
  elif [ "$1" = "BISHOP" ]; then
    piece=`echo -e "\xE2\x99\x9D"`
  elif [ "$1" = "KNIGHT" ]; then
    piece=`echo -e "\xE2\x99\x9E"`
  elif [ "$1" = "PAWN" ]; then
    piece=`echo -e "\xE2\x99\x9F"`
  else
    piece=" "
  fi
}

function getFile {
  if [ "$1" = "a" ]; then file=0; elif [ "$1" = "b" ]; then file=1; elif [ "$1" = "c" ]; then file=2
  elif [ "$1" = "d" ]; then file=3; elif [ "$1" = "e" ]; then file=4; elif [ "$1" = "f" ]; then file=5
  elif [ "$1" = "g" ]; then file=6; elif [ "$1" = "h" ]; then file=7; else file="error"; fi
}

function invalidMove {
  move="invalid"
  explanation="$1"
}

horiz="  -----------------------------------------"
alpha="    A    B    C    D    E    F    G    H"
function drawBoard {
  echo -e "$alpha"
  echo "$horiz"
  for i in {0..7}; do
    eval ${grid[i]}
    echo -n `expr $i + 1`" "
    for j in {0..7}; do
      getPiece ${row[j]}

      echo -n "| "$piece"  "
      if [ "$j" = "7" ]; then
        echo -n "|"
      fi
    done
    echo -n " "`expr $i + 1`

    echo
    echo "$horiz"
  done
  echo -e "$alpha"
}

function getMove {
  while [ -z "$move" ]; do
    echo "$explanation"
    if ! [ -z "$explanation" ]; then
      echo "$explantation"
    fi
    echo -n "Your move: "
    read input
    move=`echo "$input" | grep -oE "^[a-h][1-8]\s*[a-h][1-8]$"`
    move=`echo $move | sed 's/\s*//g'`
    if [ ! "$move" ]; then
      explanation="Invalid move syntax"
    fi
  done
}

function movePiece {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4; swapForQueen=$5

  # insert blank where src once was
  eval ${grid[srcRow]}
  src=${row[srcFile]}
  row[$srcFile]="blank"
  list=`echo ${row[@]}`
  grid[$srcRow]='row=('$list')'

  # replace target with src
  eval ${grid[targetRow]}
  target=${row[targetFile]}
  if [ $swapForQueen = "1" ]; then
    row[$targetFile]="QUEEN"
  else
    row[$targetFile]=$src
  fi
  list=`echo ${row[@]}`
  grid[$targetRow]='row=('$list')'

  if [ $captureAttempt != 0 ]; then
    captureMessage="Opponent's $target captured!"
  else
    captureMessage=""
  fi

  if [ $swapKingAndRook = "1" ]; then
    swapKingAndRook="0"
    movePiece "7" "7" "5" "7" "0"
  fi
}

function checkVerticalPath {
  # assume srcFile = targetFile
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rowDiff=`expr $targetRow - $srcRow`
  if [ "$rowDiff" -gt "0" ]; then
    i=1
    while [[ "$i" -lt $rowDiff ]]; do
      rowIdx=`expr $srcRow + $i`

      eval ${grid[rowIdx]}
      piece=${row[srcFile]}

      if [ "$piece" != "blank" ]; then
        file=`echo $srcFile | tr 01234567 abcdefgh`
        row=`echo $rowIdx | tr 01234567 12345678`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$rowDiff
      fi

      i=`expr $i + 1`
    done
  else
    i="-1"
    while [[ "$i" -gt $rowDiff ]]; do
      rowIdx=`expr $srcRow + $i`

      eval ${grid[rowIdx]}
      piece=${row[srcFile]}

      if [ "$piece" != "blank" ]; then
        file=`echo $srcFile | tr 01234567 abcdefgh`
        row=`echo $rowIdx | tr 01234567 12345678`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$rowDiff
      fi

      i=`expr $i - 1`
    done
  fi
}

function checkHorizontalPath {
  # assume srcRow = targetRow
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  fileDiff=`expr $targetFile - $srcFile`
  if [ "$fileDiff" -gt "0" ]; then
    i=1
    while [[ "$i" -lt $fileDiff ]]; do
      fileIdx=`expr $srcFile + $i`

      eval ${grid[srcRow]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $srcRow | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i + 1`
    done
  else
    i="-1"
    while [[ "$i" -gt $fileDiff ]]; do
      fileIdx=`expr $srcFile + $i`

      eval ${grid[srcRow]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $srcRow | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i - 1`
    done
  fi
}

function checkDiagonalPath {
  # assume srcRow = targetRow
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  fileDiff=`expr $targetFile - $srcFile`
  rowDiff=`expr $targetRow - $srcRow`

  if [[ "$fileDiff" -gt "0" && "$rowDiff" -gt "0" ]]; then
    i=1
    j=1
    while [[ "$i" -lt $fileDiff && "$j" -lt $rowDiff ]]; do
      fileIdx=`expr $srcFile + $i`
      rowIdx=`expr $srcRow + $j`

      eval ${grid[rowIdx]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $rowIdx | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i + 1`
      j=`expr $j + 1`
    done
  elif [[ "$fileDiff" -gt "0" && "$rowDiff" -le "0" ]]; then
    i=1
    j="-1"
    while [[ "$i" -lt $fileDiff && "$j" -gt $rowDiff ]]; do
      fileIdx=`expr $srcFile + $i`
      rowIdx=`expr $srcRow + $j`

      eval ${grid[rowIdx]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $rowIdx | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i + 1`
      j=`expr $j - 1`
    done
  elif [[ "$fileDiff" -le "0" && "$rowDiff" -gt "0" ]]; then
    i="-1"
    j=1
    while [[ "$i" -gt $fileDiff && "$j" -lt $rowDiff ]]; do
      fileIdx=`expr $srcFile + $i`
      rowIdx=`expr $srcRow + $j`

      eval ${grid[rowIdx]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $rowIdx | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i - 1`
      j=`expr $j + 1`
    done
  else
    # "$fileDiff" -le "0" && "$rowDiff" -le "0"
    i="-1"
    j="-1"
    while [[ "$i" -gt $fileDiff && "$j" -gt $rowDiff ]]; do
      fileIdx=`expr $srcFile + $i`
      rowIdx=`expr $srcRow + $j`

      eval ${grid[rowIdx]}
      piece=${row[fileIdx]}

      if [ "$piece" != "blank" ]; then
        row=`echo $rowIdx | tr 01234567 12345678`
        file=`echo $fileIdx | tr 01234567 abcdefgh`
        invalidMove "There is a piece in between those two points: $piece $file$row"
        # break
        i=$fileDiff
      fi

      i=`expr $i - 1`
      j=`expr $j - 1`
    done
  fi
}

queenAlive="1"
function movePawn {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rowDiff=`expr $targetRow - $srcRow`
  rowChange="-1"
  fileDiff=`expr $targetFile - $srcFile`
  fileDiff=`echo ${fileDiff#-}`
  fileChange="0"
  if [ "$srcRow" = "6" ]; then
    # double move allowed
    rowChange="-2"
    # if we're moving 2 spaces forward
    # make sure there's nothing in between
    between=`expr $srcRow - 1`
    eval ${grid[between]}
    between=${row[srcFile]}
  else
    between="blank"
  fi
  if [ $captureAttempt = "1" ];then
    fileChange="1"
    rowChange="-1"
  fi

  if [[ "$rowDiff" -lt "$rowChange" || $rowDiff = "0" || "$fileDiff" != "$fileChange" || "$between" != "blank" ]]; then
    invalidMove "Pawn can't move that way"
  fi
}

function moveKnight {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  prevFile=`expr $srcFile - 1`
  nextFile=`expr $srcFile + 1`
  prevRow=`expr $srcRow - 1`
  nextRow=`expr $srcRow + 1`

  jumpPrevFile=`expr $srcFile - 2`
  jumpNextFile=`expr $srcFile + 2`
  jumpPrevRow=`expr $srcRow - 2`
  jumpNextRow=`expr $srcRow + 2`

  if [[ $targetFile = $prevFile && $targetRow = $jumpPrevRow ||
    $targetFile = $nextFile && $targetRow = $jumpPrevRow ||
    $targetFile = $jumpNextFile && $targetRow = $prevRow ||
    $targetFile = $jumpNextFile && $targetRow = $nextRow ||
    $targetFile = $prevFile && $targetRow = $jumpNextRow ||
    $targetFile = $nextFile && $targetRow = $jumpNextRow ||
    $targetFile = $jumpPrevFile && $targetRow = $prevRow ||
    $targetFile = $jumpPrevFile && $targetRow = $nextRow ]]; then

    echo -n ''
    # valid move

    # check player's own piece is not in target space
  else
    # If move not in set of possible moves
    invalidMove "Knight can't move that way"
  fi
}

function rookReady {
  eval ${grid[7]}
  if [ ${row[7]} = "ROOK" ]; then
    rookReady="1"
  else
    rookReady="0"
  fi
}

function moveKing {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rookReady

  if [[ $srcRow != "7" || $targetRow != "7" || $srcFile != "4" || $targetFile != "6" || $rookReady != "1" ]]; then
    rowDiff=`expr $targetRow - $srcRow`
    rowDiff=`echo ${rowDiff#-}`
    fileDiff=`expr $targetFile - $srcFile`
    fileDiff=`echo ${fileDiff#-}`

    if [[ "$rowDiff" -gt "1" || $fileDiff -gt "1" ]]; then
      invalidMove "King can't move that way"
    fi
  else
    swapKingAndRook="1"
  fi
}

function moveRook {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rowDiff=`expr $targetRow - $srcRow`
  rowDiff=`echo ${rowDiff#-}`
  fileDiff=`expr $targetFile - $srcFile`
  fileDiff=`echo ${fileDiff#-}`

  if [[ ( $rowDiff -gt 0 && $fileDiff -gt 0 ) || ( $rowDiff = 0 && $fileDiff = 0 ) ]]; then
    invalidMove "Rook can't move that way"
  elif [ $fileDiff = "0" ]; then
    checkVerticalPath $srcFile $srcRow $targetFile $targetRow
  else
    checkHorizontalPath $srcFile $srcRow $targetFile $targetRow
  fi
}

function moveBishop {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rowDiff=`expr $targetRow - $srcRow`
  rowDiff=`echo ${rowDiff#-}`
  fileDiff=`expr $targetFile - $srcFile`
  fileDiff=`echo ${fileDiff#-}`

  if [[ ( $rowDiff != $fileDiff ) || ( $rowDiff = 0 && $fileDiff = 0 ) ]]; then
    invalidMove "Bishop can't move that way"
  else
    checkDiagonalPath $srcFile $srcRow $targetFile $targetRow
  fi
}

function moveQueen {
  srcFile=$1; srcRow=$2; targetFile=$3; targetRow=$4

  rowDiff=`expr $targetRow - $srcRow`
  rowDiff=`echo ${rowDiff#-}`
  fileDiff=`expr $targetFile - $srcFile`
  fileDiff=`echo ${fileDiff#-}`

  # combination of rook and bishop
  if [[ $rowDiff -gt 0 && $fileDiff -gt 0 ]]; then
    if [[ ( $rowDiff != $fileDiff ) ]]; then
      invalidMove "Queen can't move that way"
    else
      checkDiagonalPath $srcFile $srcRow $targetFile $targetRow
    fi
  else
    if [ $fileDiff = "0" ]; then
      checkVerticalPath $srcFile $srcRow $targetFile $targetRow
    else
      checkHorizontalPath $srcFile $srcRow $targetFile $targetRow
    fi
  fi
}

function performMove {
  move=$1
  color=$2
  swapKingAndRook="0"
  empty=0

  src=`echo ${move:0:2}`
  srcRow=`echo "$src" | grep -Eo "[1-8]"`
  srcRow=`expr $srcRow - 1`
  srcFile=`echo "$src" | grep -Eo "[a-h]"`
  getFile $srcFile
  srcFile=$file

  target=`echo ${move:2:4}`
  targetRow=`echo "$target" | grep -Eo "[1-8]"`
  targetRow=`expr $targetRow - 1`
  targetFile=`echo "$target" | grep -Eo "[a-h]"`
  getFile $targetFile
  targetFile=$file

  if [ "$file" = "error" ]; then
    invalidMove "Cannot parse out file"
  else
    eval ${grid[srcRow]}
    piece=${row[srcFile]}
    pieceColor=`echo "$piece" | grep -Eo "[A-Z]"`
    if [[ -z "$pieceColor" && "$piece" != "blank" ]]; then
      pieceColor="white"
    elif [ "$piece" != "blank" ]; then
      pieceColor="black"
      lastMovedPiece=$piece
    fi

    eval ${grid[targetRow]}
    targetPiece=${row[targetFile]}
    targetPieceColor=`echo "$targetPiece" | grep -Eo "[A-Z]"`
    if [[ -z "$targetPieceColor" && "$targetPiece" != "blank" ]]; then
      targetPieceColor="white"
    elif [ "$targetPiece" != "blank" ]; then
      targetPieceColor="black"
    fi
    if [[ "$targetPiece" != "blank" && "$targetPieceColor" != "$color" ]]; then
      captureAttempt=1
    else
      captureAttempt=0
    fi

    swapForQueen="0"
    if [ "$piece" = "blank" ]; then
      invalidMove "There's no piece there"
    elif [ "$pieceColor" != "$color" ]; then
      invalidMove "That's not your piece"
    elif [ "$targetPieceColor" = "$color" ]; then
      invalidMove "You can't capture your own piece"
    elif [ "$piece" = "PAWN" ]; then
      movePawn $srcFile $srcRow $targetFile $targetRow
      if [[ $move != "invalid" && $targetRow = "0" && $queenAlive != "1" ]]; then
        # Queen swap
        swapForQueen="1"
      fi
    elif [ "$piece" = "ROOK" ]; then
      moveRook $srcFile $srcRow $targetFile $targetRow
    elif [ "$piece" = "KNIGHT" ]; then
      moveKnight $srcFile $srcRow $targetFile $targetRow
    elif [ "$piece" = "BISHOP" ]; then
      moveBishop $srcFile $srcRow $targetFile $targetRow
    elif [ "$piece" = "KING" ]; then
      moveKing $srcFile $srcRow $targetFile $targetRow
    elif [ "$piece" = "QUEEN" ]; then
      moveQueen $srcFile $srcRow $targetFile $targetRow
    fi

    if [ "$move" != "invalid" ]; then
      movePiece $srcFile $srcRow $targetFile $targetRow $swapForQueen
      explanation=""
    fi
  fi
}

function badLogfileSyntax {
  echo
  echo "gitwar.log has incorrect syntax!"
  echo
  exit
}

function loadGame {
  while read line; do
    myLine=`echo "$line" | grep "$me"`
    opponentLine=`echo "$line" | grep "$opponent"`
    if ! [ -z "$myLine" ]; then
      move=`echo "$line" | cut -d, -f3`
      performMove "$move" "$myColor"
      if [ "$move" = "invalid" ]; then
        badLogfileSyntax
      else
        flipBoard
      fi
    elif ! [ -z "$opponentLine" ]; then
      move=`echo "$line" | cut -d, -f3`
      performMove "$move" "$opponentColor"
      if [ "$move" = "invalid" ]; then
        badLogfileSyntax
      else
        flipBoard
      fi
    else
      badLogfileSyntax
    fi
    move=""
  done < <(sed 1d "$logfile")
}

# Initialize some gitwar stuff
logfile="gitwar.log"
me=`git config "user.name"`
users1=`head -1 gitwar.users`
users2=`tail -1 gitwar.users`

# Check that the user can play and get the opponent's score
user1=`echo $users1 | cut -d" " -f1`
user2=`echo $users2 | cut -d" " -f1`
if [ "$me" = "$user1" ]; then
  opponent="$user2"
  myColor=`echo $users1 | cut -d" " -f2`
  opponentColor=`echo $users2 | cut -d" " -f2`
elif [ "$me" = "$user2" ]; then
  opponent="$user1"
  myColor=`echo $users2 | cut -d" " -f2`
  opponentColor=`echo $users1 | cut -d" " -f2`
else
  echo "You are not a player in this game. Check your git config for your 'user.name' setting. It should match one of the names in the gitwar.users file"
  echo
  exit
fi

# Actual game stuff
loadGame
drawBoard

# Game loop
while [[ -z "$move" || "$move" = "invalid" ]]; do
  move=""
  getMove
  performMove "$move" "$myColor"
  if [ "$move" != "invalid" ]; then
    if ! [ -z "$captureMessage" ]; then
      echo
      echo $captureMessage
      echo
    fi

    # save to gitwar.log
    echo "`date "+%Y-%m-%d %H:%M:%S %z"`,$me,$move" >> "$logfile"

    move=""
    drawBoard

    ../gitwar "$me took turn"

    # Just got a move from our opponent
    move=`tail -1 "$logfile" | cut -d, -f3`
    flipBoard
    color=$opponentColor
    performMove "$move" "$opponentColor"
    flipBoard
  fi
done
